import {
  FaPython,
  FaDocker,
  FaAws,
  FaReact,
  FaNodeJs,
  FaGitAlt,
  FaJava,
  FaDatabase,
  FaTerminal,
  FaLock,
  FaUnity,
  FaJenkins,
} from "react-icons/fa";
import {
  SiKubernetes,
  SiTensorflow,
  SiMysql,
  SiGrafana,
  SiCsharp,
  SiCplusplus,
  SiTerraform,
  SiPytorch,
  SiGooglecloud,
} from "react-icons/si";
import { BiLogoGoLang, BiLogoJava } from "react-icons/bi";

export const iconsAndTitles = [
  { icon: <FaPython className="text-8xl" />, title: "Python" },
  { icon: <FaDocker className="text-8xl" />, title: "Docker" },
  { icon: <SiCsharp className="text-8xl" />, title: "C#" },
  { icon: <SiKubernetes className="text-8xl" />, title: "Kubernetes" },
  { icon: <SiTensorflow className="text-8xl" />, title: "Tensorflow" },
  { icon: <FaUnity className="text-8xl" />, title: "Unity" },
  { icon: <FaAws className="text-8xl" />, title: "AWS" },
  { icon: <SiMysql className="text-8xl" />, title: "MySQL" },
  { icon: <SiGrafana className="text-8xl" />, title: "Grafana" },
  { icon: <FaReact className="text-8xl" />, title: "React" },
  { icon: <FaNodeJs className="text-8xl" />, title: "Node.js" },
  { icon: <BiLogoJava className="text-8xl" />, title: "Java" },
  { icon: <SiCplusplus className="text-8xl" />, title: "C++" },
  { icon: <FaJenkins className="text-8xl" />, title: "Jenkins" },
  { icon: <SiTerraform className="text-8xl" />, title: "Terraform" },
  { icon: <SiPytorch className="text-8xl" />, title: "PyTorch" },
  { icon: <BiLogoGoLang className="text-8xl" />, title: "Golang" },
  { icon: <FaGitAlt className="text-8xl" />, title: "Git" },
  { icon: <FaJava className="text-8xl" />, title: "Java" },
  { icon: <SiGooglecloud className="text-8xl" />, title: "GCP" },
  { icon: <FaDatabase className="text-8xl" />, title: "Database Management" },
  { icon: <FaTerminal className="text-8xl" />, title: "Bash" },
  { icon: <FaLock className="text-8xl" />, title: "Security" },
];
